INSERT INTO offer(id,bedrooms,"cityId","hostId",description,goods,images,is_favorite,is_premium,max_adults,preview_image,price,rating,title,type) VALUES (3,3,2,3,'Hi Guys. I am back with an update of the renowned Gabbie Carter. Even my uncle was like, "You should bring back that really popular porn star from Texas, the one with the insane tits". Well, family comes first. Here you go. This is Gabbie in her most natural of states.','{Heating,Kitchen,"Cable TV","Washing machine","Coffee machine",Dishwasher}','{img/d1.jpg,img/d2.jpg,img/d3.jpg}','False','False',4,'img/d1.jpg',120,4.0,'Gabbie Carter Texas Snow','apartment');
INSERT INTO offer(id,bedrooms,"cityId","hostId",description,goods,images,is_favorite,is_premium,max_adults,preview_image,price,rating,title,type) VALUES (9,3,1,31,'The worst thing about Zishy is that I am horrible at marketing. The best thing about Zishy is that I am horrible at marketing. You will not find a ton of nude imagery in this gallery, but I assume you all have seen a butthole and some vulva before.','{Heating,Kitchen,"Cable TV","Washing machine","Coffee machine",Dishwasher}','{img/cc1.jpg,img/cc2.jpg,img/cc3.jpg,img/cc4.jpg,img/cc5.jpg,img/cc6.jpg}','True','True',7,'img/cc1.jpg',333,3.3,'Emily Cutie Bungeons And Dragons','bungalo');
INSERT INTO offer(id,bedrooms,"cityId","hostId",description,goods,images,is_favorite,is_premium,max_adults,preview_image,price,rating,title,type) VALUES (10,1,1,1,'Winter freeze coming to my area. But I''m planning to add a bonus video to this update tomorrow. Hopefully, the power doesn''t go out and people don''t die and what not. Sasha Apex, a lot of personality.','{Heating,Kitchen,"Cable TV","Washing machine","Coffee machine",Dishwasher}','{img/gg1.jpg,img/gg2.jpg,img/gg3.jpg,img/gg4.jpg,img/gg5.jpg,img/gg6.jpg}','False','True',3,'img/gg1.jpg',590,2.7,'Sasha Apex Five Percent Strawb','hostel');
INSERT INTO offer(id,bedrooms,"cityId","hostId",description,goods,images,is_favorite,is_premium,max_adults,preview_image,price,rating,title,type) VALUES (11,100,3,2,'The main difference I have discerned between good art and bad art is how much it pleases others. The degree to which the artist taps into the taste of the crowd is everything.','{"Cable TV","Washing machine","Coffee machine",Dishwasher}','{img/vv1.jpg,img/vv2.jpg,img/vv3.jpg,img/vv4.jpg,img/vv5.jpg,img/vv6.jpg}','True','True',100,'img/vv1.jpg',1100,1.5,'Oakley Jacobs Ripped Knickers Gotta Go','Farmhouse');
INSERT INTO offer(id,bedrooms,"cityId","hostId",description,goods,images,is_favorite,is_premium,max_adults,preview_image,price,rating,title,type) VALUES (12,3,3,2,'Patience Dolder surprised me a little when she whipped out her restraints. I quickly realized that I had judged this book by its cover. With all her cute, quirky, vegan, gluten-free, animal shelter volunteer persona, I was blind to this darker, kinkier side of Patience.','{Heating,Kitchen,"Cable TV","Washing machine"}','{img/xx1.jpg,img/xx2.jpg,img/xx3.jpg,img/xx4.jpg,img/xx5.jpg,img/xx6.jpg}','True','True',8,'img/xx1.jpg',105,0.9,'Patience Dolder Because I Can','Chalet');
INSERT INTO offer(id,bedrooms,"cityId","hostId",description,goods,images,is_favorite,is_premium,max_adults,preview_image,price,rating,title,type) VALUES (13,7,3,5,'It doesn''t matter if you are a bigot, it only matters that you avoid doing anything, at all costs, that can be viewed as offensive by anyone. Oh well. Gabbie is still probably pretty fun, and wild, and troubled.','{"Coffee machine",Dishwasher}','{img/dd1.webp,img/dd2.webp,img/dd3.webp,img/dd4.webp,img/dd5.webp,img/dd6.webp}','True','False',13,'img/dd1.webp',705,3.1,'Gabbie Carter Home Video','Farmhouse');

INSERT INTO location(latitude,longitude,zoom,"cityId") VALUES ('48.01458633570351','37.800630564034506',10,3);
INSERT INTO location(latitude,longitude,zoom,"cityId") VALUES ('55.751244','37.618423',10,1);
INSERT INTO location(latitude,longitude,zoom,"cityId") VALUES ('57.6260744','39.8844708',10,2);

INSERT INTO "offerLocation"(id,latitude,longitude,zoom,"offerId") VALUES (3,'57.62902889944186','39.8970462330394',8,3);
INSERT INTO "offerLocation"(id,latitude,longitude,zoom,"offerId") VALUES (9,'55.77722651847531','37.57803719046799',8,9);
INSERT INTO "offerLocation"(id,latitude,longitude,zoom,"offerId") VALUES (10,'55.78717173002577','37.66677730889082',8,10);
INSERT INTO "offerLocation"(id,latitude,longitude,zoom,"offerId") VALUES (11,'48.03674842676716','37.75187759767552',8,11);
INSERT INTO "offerLocation"(id,latitude,longitude,zoom,"offerId") VALUES (12,'48.00575369717381','37.87068761151003',8,12);
INSERT INTO "offerLocation"(id,latitude,longitude,zoom,"offerId") VALUES (13,'47.985471481838516','37.82249114705648',8,13);